---
title: "purrr"
author: "Mine Cetinkaya-Rundel"
date: "October 26, 2017"
output: ioslides_presentation
---

```{r setup, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Welcome to R-Ladies RTP!

## Materials

- All source code at ???
    - Download the contents of the repo, we'll need the R scripts and data in the apps folder

- Slides at ???

## Acknowledgements

- Charlotte Whickham - [Purrr tutorial](https://github.com/cwickham/purrr-tutorial)
- Colin Rundel - [Functional programming](http://www2.stat.duke.edu/~cr173/Sta523_Fa17/functional.html)
- Hadley Wickham - [Adv-R Functionals](http://adv-r.had.co.nz/Functionals.html)
- Hadley Wickham - [R for Data Science](http://r4ds.had.co.nz/)
- Neil Saunders - [A brief introduction to "apply" in R](http://nsaunders.wordpress.com/2010/08/20/a-brief-introduction-to-apply-in-r/)
- Jenny Bryan - [Purrr Tutorial](https://jennybc.github.io/purrr-tutorial/)
- [R Language Definition](http://stat.ethz.ch/R-manual/R-devel/doc/manual/R-lang.html)

# Outline

## Outline

- Code with a lot of duplication is harder to understand, troubleshoot and maintain. The goal of this tutorial is help you remove duplication in your code by using functions that write for loops for you.

- You'll learn to use the functions in the purrr package to perform iterative tasks: tasks that look like "for each _____ do _____".

- The goal is to make strides towards writing code that is more readable and easier to update and so that you are ready to solve new iteration problems faster and with fewer mistakes.

## Learning goals

By the end of the workshop, you'll be able to:

- Move from solving a problem on a single element, to iterating that solution over many elements with `map()`.
- Use **purrr** to work with list columns in tibbles.
- Leverage **purrr** to get list data into tibbles.

???
- Identify when to use the typed variants of map(): map_lgl(), map_int(), walk() etc.
- Iterate over two arguments with map2().

# 